name: 'zigist'
description: 'Elevate your profile with a pinned gist of a random dev joke'
branding:
  icon: zap
  color: yellow
inputs:
  gh-token:
    description: 'Github token'
    required: true
  gist-id:
    description: 'Gist id'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh-token }}
    - ${{ inputs.gist-id }}
