name: cron
on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    name: A job update a gist with a random dev joke
    steps:
      - name: Update gist action step
        id: zigist
        uses: lmllrjr/zigist@v1
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          gist-id: ${{ vars.GIST_ID }}
