name: test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: ${{ vars.GIST_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build test --summary all

  test-github-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Update gist action step
        id: zigist
        uses: lmllrjr/zigist@v1
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          gist-id: 'd0313228583992554c58c626b7df7f2f'
