name: test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: ${{ vars.GIST_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build test --summary all
